var presiNames = ['George Washington',
'George Washington',
'John Adams',
'Thomas Jefferson',
'Thomas Jefferson',
'James Madison',
'James Madison',
'James Monroe',
'James Monroe',
'John Quincy Adams',
'Andrew Jackson',
'Andrew Jackson',
'Martin Van Buren',
'William Henry Harrison',
'James Knox Polk',
'Zachary Taylor',
'Franklin Pierce',
'James Buchanan',
'Abraham Lincoln',
'Abraham Lincoln',
'Ulysses S. Grant',
'Ulysses S. Grant',
'Rutherford B. Hayes',
'James A. Garfield',
'Grover Cleveland',
'Benjamin Harrison',
'Grover Cleveland',
'William McKinley',
'William McKinley',
'Theodore Roosevelt',
'William Howard Taft',
'Woodrow Wilson',
'Woodrow Wilson',
'Warren G. Harding',
'Calvin Coolidge',
'Herbert Hoover',
'Franklin D. Roosevelt',
'Franklin D. Roosevelt',
'Franklin D. Roosevelt',
'Franklin D. Roosevelt',
'Harry S. Truman',
'Dwight D. Eisenhower',
'Dwight D. Eisenhower',
'John F. Kennedy',
'Lyndon Baines Johnson',
'Richard Milhous Nixon',
'Richard Milhous Nixon',
'Jimmy Carter',
'Ronald Reagan',
'Ronald Reagan',
'George Bush',
'Bill Clinton',
'Bill Clinton',
'George W. Bush',
'George W. Bush',
'Barack Obama',
'Barack Obama',
'Donald J. Trump']